### ISSUE TITLE
AbixApuri ei siirrä koetuloksia Exceliin

### ISSUE THREAD

**Issue by moianj** [klo33/abixapuri#18]
Excel ei avaa tiedostoa - sisältö eri muotoa kuin tunniste tms, en muista enää tarkkaa sanamuotoa.

**Comment by klo33** [comment]
Vika on itseasiassa Excelissä, sillä jostain syystä Excel ei osaa tulkita CSV-tiedostoa oikein, kun sen ensimmäisenä sarakeotsikkona on ID. Esim. LibreOffice avaa tiedoston ongelmitta ja osaa jopa tulkita ääkköset oikein kun käyttää UTF-8-merkistöä.

v0.5.4 on sarakeotsikko vaihdettu muuhun tekstiin, jotta Excelkin osaa avata tiedoston.
