### ISSUE TITLE
Ongelmia Apurissa? 

### ISSUE THREAD

**Issue by karmlee** [klo33/abixapuri#19]
Hei, olen tehnyt Abittikoetta Chromessa Apurin kera ja minulta häviää tehtäviä ja niiden järjestys myös muuttuu. Hjälp!

**Comment by jonilehtola** [comment]
Valitettavasti tästä yleisestä kommentista en pysty toisintamaan tilannetta. En ole omissa testeissäni tai päivittäisessä käytössä kohdannut vastaavaa, jolloin haluaisin saada _tarkan yhteenvedon_ a) millä sivulla olit ja mitä tietoa olit syöttänyt b) mitä toimintoa yritit käyttää c) mitä tarkalleen ottaen teit. Mieluiten kokeen siirtotiedoston kera. Lisäksi AbixApurista on olemassa userscript ja selainlisäosa versio, mitä käytit? Mikä on Chromen versiosi?

**Comment by klo33** [comment]
Mahdolliseen ongelmaan ei ole saatu vastausta, joten suljen ongelman. Tilanne voisi johtua esim. saman kokeen auki olemisesta usealla selaimen välilehdellä, jolloin ongelma johtuu siis oma.abitti.fi-palvelun rakenteesta ja toiminnasta.
