### ISSUE TITLE
Koetehtävien uudelleenjärjestely ei toimi B-osan tehtävissä.

### ISSUE THREAD

**Issue by mikojanus** [klo33/abixapuri#20]
Luo abittikoe, johon 2 tehtävää A-osaan ja 2 B-osaan. 
Valitse tehtävien uudellenjärjestäminen ja A-osassa pystyt vaihtamaan järjestystä, mutta B-osassa ei.
Lisäksi olisi hyvä, jos B-osan tehtäviä voisi siirtää A-osaan - muuten valmiiden koepakettien hyödyntäminen ei onnistu.

**Comment by mikojanus** [comment]
Asensin apurin uudestaan, ja alkoikin toimia.

**Comment by klo33** [comment]
Pitäisi toimia oikein tosiaan versiosta v0.6.0 alkaen. Kannattaa varmistaa selaimesta, että lisäosa on päivittynyt. Tällöin AbixApuri tukee myös tehtävien siirtoa osien välillä.
