### ISSUE TITLE
Apuri lakkaa toimimasta palautuksessa

### ISSUE THREAD

**Issue by kirmus** [klo33/abixapuri#21]
Jostain syystä Abix apuri lakkaa toimimasta todella usein, kun menen abittikokeen palautuksiin. En pysty käyttämään arvosanalaskuria ym., mutta kokeen palautus opiskelijoiden sähköposteihin onnistuu. Olisko neuvoa tähän?

**Comment by klo33** [comment]
Tästä ei ole kuulunut lisätietoja. .MEX-kokeissa on ollut ongelmia ennen versiota v0.8.3, mutta keväällä 2019 ei vielä ole ollut mahdollista tehdä uuden formaatin kokeita. Suljen ongelman, mutta jos se toistuu niin jos saat lisätietoja selaimen kehitysikkunasta (Ctrl-Shift-I > Valitse Console ja kopioi kaikki tänne) niin ongelman selvitys helpottuu.
