### ISSUE TITLE
YO-kokeesta tehtävän kopioimisen jälkeen oma koe ei toimi

### ISSUE THREAD

**Issue by NoPunIntended78** [klo33/abixapuri#22]
Kopioin ylioppilaskokeesta yhden tehtävän (AbixApurilla) omaan kurssikokeena aikomaani kokeeseen, ja tämän jälkeen Abitti ilmoittaa minulle, että en voi enää muokata koettani ollenkaan. Onko jotain tehtävissä, vai pitääkö alkaa tehdä koetta kokonaan uusiksi?

**Comment by klo33** [comment]
Jos koetta, josta tehtävä kopioidaan, ei voi editoida Abitissa, ei välttämättä voi editoida myöskään koetta, johon tehtävä on tuotu, koska tehtävä sisältää koodia tai rakenteita, joita Abitin editori ei pysty käsittelemään. Tämä on lähtökohtaisesti Abitin ominaisuus, ei Apurin puute. Todennäköisesti koe, johon tehtävä on tuotu, voi käyttää kokeena.
