### ISSUE TITLE
Ei asennu

### ISSUE THREAD

**Issue by juliusvonm** [klo33/abixapuri#27]
"This add-on could not be installed because it has not been verified."

Abixapuri 0.8.3.0
Firexfox 88.0.1
MacOS 10.15

**Comment by juha-anttila** [comment]
Sama ongelma, lisäosaa ei varmennettu. Käsittääkseni Firefoxin päädyn ongelma.

Abixapuri 0.8.3.0
Firefox 93.0
Windows 10

Onko mahdollista saada vanhempia abixapurin versioita ladattavaksi? Versio 0.6.2 on käytössä ja toimii, mutta osapisteytyksen ominaisuutta ei ole. Muistaakseni 0.8.0 versio toimi vielä, mutta ei ole työkoneella käytössä, eikä päivitys 0.8.3 suostu edellä mainitusta syystä asentumaan.

Edit:
Löysin edellä mainitun version muokkaamalla latauslinkkiä manuaalisesti:
https://github.com/klo33/abixapuri/blob/master/dist/abixapuri-0.8.0.0-an+fx.xpi?raw=true

**Comment by klo33** [comment]
Päivitys versioon 0.9.2 pitäisi korjata ongelmat.
